#!/usr/bin/env bash


###
# pssh 1.0
# a ssh abstraction layer (c) Point Inside @ Greg Nokes
###

###
# We accept a single commandline argument
# the server that you want to pssh to
# or list to generate a list of psshable servers
###

ruby ./lib/pssh.rb $1